"""Initial schema

Revision ID: df5d6f9f9aa8
Revises: 
Create Date: 2026-09-20 21:53:09.656110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df5d6f9f9aa8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('public_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent', sa.String(length=128), nullable=True),
    sa.Column('tool', sa.String(length=128), nullable=True),
    sa.Column('requested_scope', sa.String(length=255), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('delegation_id', sa.String(length=128), nullable=True),
    sa.Column('detail', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_audit_events_agent'), 'audit_events', ['agent'], unique=False)
    op.create_index(op.f('ix_audit_events_delegation_id'), 'audit_events', ['delegation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_tool'), 'audit_events', ['tool'], unique=False)
    op.create_table('revocations',
    sa.Column('delegation_id', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('revoked_by', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('delegation_id')
    )
    op.create_table('delegations',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('issuer_id', sa.String(length=128), nullable=False),
    sa.Column('subject_id', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.String(length=128), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('credential_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['delegations.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delegations_issuer_id'), 'delegations', ['issuer_id'], unique=False)
    op.create_index(op.f('ix_delegations_parent_id'), 'delegations', ['parent_id'], unique=False)
    op.create_index(op.f('ix_delegations_subject_id'), 'delegations', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delegations_subject_id'), table_name='delegations')
    op.drop_index(op.f('ix_delegations_parent_id'), table_name='delegations')
    op.drop_index(op.f('ix_delegations_issuer_id'), table_name='delegations')
    op.drop_table('delegations')
    op.drop_table('revocations')
    op.drop_index(op.f('ix_audit_events_tool'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_delegation_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_agent'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('agents')
    # ### end Alembic commands ###
