"""Initial schema with organizations

Revision ID: e41ee27ec83f
Revises: 
Create Date: 2026-09-21 14:49:40.333074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41ee27ec83f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent', sa.String(length=128), nullable=True),
    sa.Column('tool', sa.String(length=128), nullable=True),
    sa.Column('requested_scope', sa.String(length=255), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('delegation_id', sa.String(length=128), nullable=True),
    sa.Column('detail', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_agent'), ['agent'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_delegation_id'), ['delegation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_tool'), ['tool'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('revocations',
    sa.Column('delegation_id', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('revoked_by', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('delegation_id', name=op.f('pk_revocations'))
    )
    op.create_table('agents',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('organization_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('public_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_agents_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_organization_id'), ['organization_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('organization_id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    op.create_table('delegations',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('organization_id', sa.String(length=128), nullable=True),
    sa.Column('issuer_id', sa.String(length=128), nullable=False),
    sa.Column('subject_id', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.String(length=128), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('credential_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['issuer_id'], ['agents.id'], name=op.f('fk_delegations_issuer_id_agents')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_delegations_organization_id_organizations')),
    sa.ForeignKeyConstraint(['parent_id'], ['delegations.id'], name=op.f('fk_delegations_parent_id_delegations')),
    sa.ForeignKeyConstraint(['subject_id'], ['agents.id'], name=op.f('fk_delegations_subject_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delegations'))
    )
    with op.batch_alter_table('delegations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delegations_issuer_id'), ['issuer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegations_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delegations_subject_id'), ['subject_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delegations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delegations_subject_id'))
        batch_op.drop_index(batch_op.f('ix_delegations_parent_id'))
        batch_op.drop_index(batch_op.f('ix_delegations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_delegations_issuer_id'))

    op.drop_table('delegations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_organization_id'))

    op.drop_table('agents')
    op.drop_table('revocations')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_tool'))
        batch_op.drop_index(batch_op.f('ix_audit_events_delegation_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_agent'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
